@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":Coach2K22Parser" as Coach2K22Parser LOGIC_COLOR
participant ":AddTaskTagCommandParser" as AddTaskTagCommandParser LOGIC_COLOR
participant "p:AddTaskTagCommand" as AddTaskTagCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("tag-add-t 1 important")
activate LogicManager

LogicManager -> Coach2K22Parser : parseCommand("tag-add-t 1 important")
activate Coach2K22Parser

create AddTaskTagCommandParser
Coach2K22Parser -> AddTaskTagCommandParser
activate AddTaskTagCommandParser

AddTaskTagCommandParser --> Coach2K22Parser
deactivate AddTaskTagCommandParser

Coach2K22Parser -> AddTaskTagCommandParser : parse(" 1 important")
activate AddTaskTagCommandParser

create AddTaskTagCommand
AddTaskTagCommandParser -> AddTaskTagCommand
activate AddTaskTagCommand

AddTaskTagCommand --> AddTaskTagCommandParser : p
deactivate AddTaskTagCommand

AddTaskTagCommandParser --> Coach2K22Parser : p
deactivate AddTaskTagCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddTaskTagCommandParser -[hidden]-> Coach2K22Parser
destroy AddTaskTagCommandParser

Coach2K22Parser --> LogicManager : p
deactivate Coach2K22Parser

LogicManager -> AddTaskTagCommand : execute()
activate AddTaskTagCommand

AddTaskTagCommand -> Model : setTask(taskToEdit, editedTask)
activate Model

Model --> AddTaskTagCommand
deactivate Model

create CommandResult
AddTaskTagCommand -> CommandResult
activate CommandResult

CommandResult --> AddTaskTagCommand
deactivate CommandResult

AddTaskTagCommand --> LogicManager : result
deactivate AddTaskTagCommand

[<--LogicManager
deactivate LogicManager
@enduml
