@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":Coach2K22Parser" as Coach2K22Parser LOGIC_COLOR
participant ":DeleteTaskTagCommandParser" as DeleteTaskTagCommandParser LOGIC_COLOR
participant "p:DeleteTaskTagCommand" as DeleteTaskTagCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("tag-del-t 1 important")
activate LogicManager

LogicManager -> Coach2K22Parser : parseCommand("tag-del-t 1 important")
activate Coach2K22Parser

create DeleteTaskTagCommandParser
Coach2K22Parser -> DeleteTaskTagCommandParser
activate DeleteTaskTagCommandParser

DeleteTaskTagCommandParser --> Coach2K22Parser
deactivate DeleteTaskTagCommandParser

Coach2K22Parser -> DeleteTaskTagCommandParser : parse(" 1 important")
activate DeleteTaskTagCommandParser

create DeleteTaskTagCommand
DeleteTaskTagCommandParser -> DeleteTaskTagCommand
activate DeleteTaskTagCommand

DeleteTaskTagCommand --> DeleteTaskTagCommandParser : p
deactivate DeleteTaskTagCommand

DeleteTaskTagCommandParser --> Coach2K22Parser : p
deactivate DeleteTaskTagCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteTaskTagCommandParser -[hidden]-> Coach2K22Parser
destroy DeleteTaskTagCommandParser

Coach2K22Parser --> LogicManager : p
deactivate Coach2K22Parser

LogicManager -> DeleteTaskTagCommand : execute()
activate DeleteTaskTagCommand

DeleteTaskTagCommand -> Model : setTask(taskToEdit, editedTask)
activate Model

Model --> DeleteTaskTagCommand
deactivate Model

create CommandResult
DeleteTaskTagCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteTaskTagCommand
deactivate CommandResult

DeleteTaskTagCommand --> LogicManager : result
deactivate DeleteTaskTagCommand

[<--LogicManager
deactivate LogicManager
@enduml
