@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":Coach2K22Parser" as Coach2K22Parser LOGIC_COLOR
participant ":DeletePersonTagCommandParser" as DeletePersonTagCommandParser LOGIC_COLOR
participant "p:DeletePersonTagCommand" as DeletePersonTagCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("tag-del-p 1 friend")
activate LogicManager

LogicManager -> Coach2K22Parser : parseCommand("tag-del-p 1 friend")
activate Coach2K22Parser

create DeletePersonTagCommandParser
Coach2K22Parser -> DeletePersonTagCommandParser
activate DeletePersonTagCommandParser

DeletePersonTagCommandParser --> Coach2K22Parser
deactivate DeletePersonTagCommandParser

Coach2K22Parser -> DeletePersonTagCommandParser : parse(" 1 friend")
activate DeletePersonTagCommandParser

create DeletePersonTagCommand
DeletePersonTagCommandParser -> DeletePersonTagCommand
activate DeletePersonTagCommand

DeletePersonTagCommand --> DeletePersonTagCommandParser : p
deactivate DeletePersonTagCommand

DeletePersonTagCommandParser --> Coach2K22Parser : p
deactivate DeletePersonTagCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeletePersonTagCommandParser -[hidden]-> Coach2K22Parser
destroy DeletePersonTagCommandParser

Coach2K22Parser --> LogicManager : p
deactivate Coach2K22Parser

LogicManager -> DeletePersonTagCommand : execute()
activate DeletePersonTagCommand

DeletePersonTagCommand -> Model : setPerson(personToEdit, editedPerson)
activate Model

Model --> DeletePersonTagCommand
deactivate Model

create CommandResult
DeletePersonTagCommand -> CommandResult
activate CommandResult

CommandResult --> DeletePersonTagCommand
deactivate CommandResult

DeletePersonTagCommand --> LogicManager : result
deactivate DeletePersonTagCommand

[<--LogicManager
deactivate LogicManager
@enduml
